// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yyfgxpaqwoveoutdjhux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5Zmd4cGFxd292ZW91dGRqaHV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1NjQxNDgsImV4cCI6MjA1NjE0MDE0OH0.mhUQMf83YKg4GtxBaW2X1VFE0I3DTKXjfc2W7zRu4rY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);